language: node_js

node_js:
  - node # latest stable node version

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/kangax/fabric.js.git
  - cd fabric.js
  - git checkout $(git describe --tags --abbrev=0) # Make sure to always checkout the latest tag
  - git submodule update --init --recursive

install:
  - npm install

script:
  - npm run build_with_gestures

before_deploy:
  - node ../replace-package-name.js ./package.json fabric-with-gestures

deploy:
  edge: true # opt in to dpl v2
  provider: npm
  email: $NPM_EMAIL
  api_token: $NPM_API_KEY
  cleanup: false
  on:
    branch: master
    # Check that the version is not already pushed by using the `npm view` command
    # This will be empty when that version does not exist
    condition: -z "$(npm view fabric-with-gestures@$(git describe --tags --abbrev=0) version)"
