language: node_js

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/kangax/fabric.js.git
  - cd fabric.js
  - git checkout $(git describe --tags --abbrev=0) # Make sure to always checkout the latest tag
  - git submodule update --init --recursive

install:
  - npm install

before_script:
  - npm install -g npm@next # upgrade to the most recent release

script:
  - npm run build_with_gestures

before_deploy:
  - node ../replace-package-name.js ./package.json fabric-with-gestures

deploy:
  skip_cleanup: true
  provider: npm
  email: ingmardelsink@hotmail.com
  api_key:
    secure: 1WwFqdbbTAS4NcIpCKOhZl5QWQKKQ439HAvsRrINhi1cS+lIe5oOp9Cv7E5rIhFa5oq4IdSkyIuvFES5efSCD8K2XXixpGE9eqDx/E4ZRJYinE7o+6UriOn5pcqwxEVZD9zXhiNhgcY6dCCAeGeVF6Q3Y9TDNaPjclR9StJDG5yWEB323wTZ2BbunTr39dIaoHLxN6gpYQZ4BirhFBgJe2h/X/bthaeI14unB3Q0U+wT8ez7hi8g5pH5Mbobr9ZQlozVSHdtFZQvmKh4SWwIm6wGb4rPVnNe1i/C+ELfcziCN8fBiLJYSihzzZT/7UnK1CFuJkYJSEYNCWaxSXR8Aib0rhZ0+8FNVOauMEnIoIx4HJRInC2fuKhgxZwgm1agkuxvspG6C7VMs7rQdP6wKGSBPlZ1jxQDHShy2t1zh51TVM3tcrA3JKeJbSLeYrnjJJxj577tCbJmya7x5YYDNcXV5DNHPLxrR79neX8x42T5Y/YWPZcyVH0rC25lJzRnqEaecoigB+Uvvf2N/ZEKYXrTUMmuqOqzlpWJVyKmL4819h3rQnzUTDD/e9gry0lpZcs7+DNR1fP3fqzUWzT3WlBW7hNihcfnaknpcDkF4NCGKz4FjbOA7su37/8vFghouWMM9GvBBInSbN+JFva4cc4fZscVZSdumXuUbLo5Vgk=
  on:
    repo: idelsink/fabric.js-autobuild
    branch: master
