language: node_js

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/kangax/fabric.js.git
  - cd fabric.js
  - git checkout $(git describe --tags --abbrev=0) # Make sure to always checkout the latest tag
  - git submodule update --init --recursive

install:
  - npm install

script:
  - npm run build_with_gestures

before_deploy:
  - node ../replace-package-name.js ./package.json fabric-with-gestures

deploy:
  skip_cleanup: true
  provider: npm
  email: ingmardelsink@hotmail.com
  api_key:
    secure: U4Ku5IWv48RNDcb84deoIPTwEXOMpQghaFrp8H0DIVpv5wT47WD2bn/MwQ86KUxh/UqR7hD9Rdv/MdpfxYYKYMaVnhpJPlVVTCg7PanlbRKELLGbiaFm8XLjpIkzmzCFx83Qrem5v2+hEwQxniDmcY0D+3J5zVgRIEVCoVFn7WuaQmCJTI/SOVoMOKNzOrL7JYPLO75Z8d1COio2+VsKpG2KTb6T0VjOIuhxKk6cEqs9zZ6huJqcS4rXxw/mxxvn8UIbiacYdGaOF3HVq+jkVpMAndgK9EhOy2XuhoQ1dfj7Vz0+HCcYCSklTDHPr3WdmaHsmpE+eZHgLFGFtrq832MdpqB2ZOvWkS1hh5+GASWKsJEcjnxqseMw6AXyrt0PZtusqHAAQ7dN5oAR6vAzCzFuHMNe9uvFMel43d8z6FjstpDkq9xLZhZ4g6wAM2dPDIk4gS+KVeRgmxuWTCH5pIwhKaInlaCzrchW8g0BND7Z8/1TUoN5ptNvfnzySCoWOFXISqV/hnkbcl/tLWl30EwI5ih3nLM5I915MAEr2m8HJPYqAaiynueRuiunj3djK2eAMg3LacopcU+eqN0CPYLq/8h8xMJIyRRbTaRnUWPvAg4miFZQ2Wr4lI/y6n3rqpfyxw7wwqBy7N/55aJCnaNcxlQSNieS8OVR1FHt4DI=
  on:
    repo: idelsink/fabric.js-autobuild
    branch: master
