language: node_js

node_js:
  - "10"

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/kangax/fabric.js.git
  - cd fabric.js
  - git checkout $(git describe --tags --abbrev=0) # Make sure to always checkout the latest tag
  - git submodule update --init --recursive

install:
  - npm install

script:
  - npm run build_with_gestures

before_deploy:
  - node ../replace-package-name.js ./package.json fabric-with-gestures

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    repo: idelsink/fabric.js-autobuild
    branch: master
