language: node_j

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone git@github.com:kangax/fabric.js.git
  - cd fabric.js

install:
  - npm install

script:
  - npm run build_with_gestures
