language: node_js

node_js:
  - "10"

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/kangax/fabric.js.git
  - cd fabric.js
  - git checkout $(git describe --tags --abbrev=0) # Make sure to always checkout the latest tag
  - git submodule update --init --recursive

install:
  - npm install

script:
  - npm run build_with_gestures

before_deploy:
  - node ../replace-package-name.js ./package.json fabric-with-gestures

deploy:
  skip_cleanup: true
  provider: npm
  email: ingmardelsink@hotmail.com
  api_key:
    secure: PjVw1k1BZlj3qKyQwK6Y1oDgbi0+O+473q1m6/wCRDzETDLiWD/PQ7ZWuXDIdhudoXOkIBQcd4nkK4zpVJIb59WpXMDoBRzi5ZdCoSKZs+Q7vCNgtV+EhTVP3LdrHePTtwd3KnBDHbycI1y9yIPf4u/DJJ1bzv8Z2vKOe8JQRwRojy1RDqUEHY7D9TgVENjVJFSl8146nsdWg96LHWrn3ap21CAod/5htBPwiFPnQWiXQ1LK0B+2QfKCiskVrB/CM5vMrsc3iGwq/wIpvUHztxq+ypmEAgLPGL7dqb6Bylex+NqESR4JhaF81j2BNt5E++6EpD0G6wyDFSUWf2DHHms20n5f5+Ag0H4P7w7XBnshQKW3QWnrhFxO9ltoPSudJYkxENcpdg8J24CKTMM5WzX4yrsiMpBjA0pfDGhsUiqflxl3KUoV/54pRiiP3CuBRMpmNhoHc0osznIq/cKfN5diErZltB+lSff6rvvIIS+ffvNF1tYT6OufJTqssJ0VyAhyaUoEN+JU9DCwryJ/6OH62lM3OkzPBKvDdcJaHEnyp4SYdz3ccQnrSHmede0ZnNlIIuNnUD6PJ8Dft4rrG5IPm3MTyyz1uVVXWcpb9/QUu7CukoPAwIdcMuJEgJUeyuPqxHB1PuN64xmi/CyaIaA3PIoqeXS6KFiHS62eLnI=
  on:
    repo: idelsink/fabric.js-autobuild
    branch: master
